Updated flake
Temporary removed rnix-lsp which was causing

error: Package ‘nix-2.15.3 ... nix/common.nix:249 is marked as insecure, refusing to evaluate.